# Generated by Django 3.1.3 on 2020-12-09 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MySchoolUser',
            fields=[
                ('myschool_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'myschool_user',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='myschooluser',
            constraint=models.UniqueConstraint(fields=('auth_user',), name='unique_auth_user_for_myschool_user'),
        ),
    ]
