# Generated by Django 3.1.3 on 2021-03-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySchoolHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('chapter_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chapter_topic',
            },
        ),
        migrations.CreateModel(
            name='MapMySchoolUserStandardSection',
            fields=[
                ('map_my_school_user_standard_section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=1)),
                ('status', models.BooleanField()),
                ('myschool_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'map_myschool_user_standard_section',
            },
        ),
        migrations.CreateModel(
            name='PaperEntry',
            fields=[
                ('paper_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_entry_name', models.CharField(max_length=100)),
                ('paper_entry_status', models.BooleanField(default=True)),
                ('paper_entry_date', models.DateField()),
            ],
            options={
                'db_table': 'paper_entry',
            },
        ),
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('paper_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_type', models.CharField(max_length=100)),
                ('out_of', models.IntegerField()),
            ],
            options={
                'db_table': 'paper_type',
            },
        ),
        migrations.CreateModel(
            name='TblStandard',
            fields=[
                ('standard', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblstandard',
            },
        ),
        migrations.CreateModel(
            name='TblSubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
                ('remembrance_credit', models.IntegerField(default=40)),
                ('applied_knowledge_credit', models.IntegerField(default=30)),
                ('understanding_credit', models.IntegerField(default=30)),
                ('subject_credit', models.IntegerField(default=100)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblstandard')),
            ],
            options={
                'db_table': 'tblsubject',
            },
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('subject_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=150)),
                ('remembrance_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('chapter_credit', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentPerformance.tblsubject')),
            ],
            options={
                'db_table': 'subject_chapter',
            },
        ),
        migrations.CreateModel(
            name='PaperPatternEntry',
            fields=[
                ('paper_pattern_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_question_id', models.IntegerField()),
                ('rau_type', models.CharField(choices=[('R', 'Remembrance'), ('A', 'Application'), ('U', 'Understanding')], max_length=1)),
                ('total_marks', models.IntegerField()),
                ('chapter_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.chaptertopic')),
                ('paper_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.paperentry')),
            ],
            options={
                'db_table': 'paper_pattern_entry',
            },
        ),
        migrations.AddField(
            model_name='paperentry',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.papertype'),
        ),
        migrations.AddField(
            model_name='paperentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblsubject'),
        ),
        migrations.CreateModel(
            name='MapStudentPaperPatternEntry',
            fields=[
                ('map_student_paper_pattern_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.IntegerField()),
                ('map_myschool_user_standard_section', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.mapmyschooluserstandardsection')),
                ('paper_pattern_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.paperpatternentry')),
            ],
            options={
                'db_table': 'map_myschool_user_paper_pattern_entry',
            },
        ),
        migrations.CreateModel(
            name='MapMySchoolUserSubject',
            fields=[
                ('map_myschool_user_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('myschool_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblsubject')),
            ],
            options={
                'db_table': 'map_myschool_user_subject',
            },
        ),
        migrations.AddField(
            model_name='mapmyschooluserstandardsection',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblstandard'),
        ),
        migrations.AddField(
            model_name='chaptertopic',
            name='subject_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.subjectchapter'),
        ),
    ]
