# Generated by Django 3.1.3 on 2020-11-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySchoolHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('chapter_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chapter_topic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarksType',
            fields=[
                ('marks_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_type', models.CharField(max_length=100)),
                ('out_of', models.IntegerField()),
            ],
            options={
                'db_table': 'marks_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaperPatternEntry',
            fields=[
                ('paper_pattern_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_pattern_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('marks_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.markstype')),
            ],
            options={
                'db_table': 'paper_pattern_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('standard', models.IntegerField()),
                ('section', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblsubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
                ('remembrance_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('subject_credit', models.IntegerField()),
                ('class_field', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblclass')),
            ],
            options={
                'db_table': 'tblsubject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('subject_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=15)),
                ('remembrance_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('chapter_credit', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblsubject')),
            ],
            options={
                'db_table': 'subject_chapter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaperPatternQuestion',
            fields=[
                ('paper_pattern_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_pattern_question_text_id', models.IntegerField()),
                ('paper_pattern_question_text', models.TextField()),
                ('rau_type', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('chapter_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.chaptertopic')),
                ('paper_pattern_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.paperpatternentry')),
            ],
            options={
                'db_table': 'paper_pattern_question',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='paperpatternentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblsubject'),
        ),
        migrations.CreateModel(
            name='MapTeacherSubject',
            fields=[
                ('map_teacher_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'map_myschool_user_subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapStudentPaperPatternQuestion',
            fields=[
                ('map_student_paper_pattern_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_obtained', models.IntegerField()),
                ('paper_pattern_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.paperpatternquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'map_myschool_user_paper_pattern_question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapMySchoolUserClass',
            fields=[
                ('map_my_school_user_class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.tblclass')),
                ('myschool_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'map_myschool_user_class',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chaptertopic',
            name='subject_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.subjectchapter'),
        ),
    ]
