# Generated by Django 3.0.8 on 2020-09-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('chapter_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chapter_topic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionGroup',
            fields=[
                ('feedback_question_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_group', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'feedback_question_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarksType',
            fields=[
                ('marks_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_type', models.CharField(max_length=100)),
                ('out_of', models.IntegerField()),
            ],
            options={
                'db_table': 'marks_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaperPatternEntry',
            fields=[
                ('paper_pattern_entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_pattern_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('marks_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.MarksType')),
            ],
            options={
                'db_table': 'paper_pattern_entry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.BigIntegerField()),
                ('email_id', models.CharField(max_length=100)),
                ('password', models.TextField()),
                ('salt', models.TextField()),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('class_field', models.CharField(db_column='class', max_length=3, primary_key=True, serialize=False)),
                ('describe', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblrole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tblrole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Person')),
            ],
            options={
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tblsubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
                ('remembarence_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('subject_credit', models.IntegerField()),
                ('class_field', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.TblClass')),
            ],
            options={
                'db_table': 'tblsubject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('subject_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=15)),
                ('remembarence_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('chapter_credit', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Tblsubject')),
            ],
            options={
                'db_table': 'subject_chapter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentEfficacy',
            fields=[
                ('student_efficacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_education', models.IntegerField()),
                ('mother_education', models.IntegerField()),
                ('internet_facility', models.IntegerField()),
                ('study_time', models.IntegerField()),
                ('paid_tution', models.IntegerField()),
                ('past_failures', models.IntegerField()),
                ('free_time', models.IntegerField()),
                ('extra_curricular_activties', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('class_engagement', models.IntegerField()),
                ('health', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Student')),
            ],
            options={
                'db_table': 'student_efficacy',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='student',
            name='class_field',
            field=models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.TblClass'),
        ),
        migrations.AddField(
            model_name='student',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Person'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Person')),
            ],
            options={
                'db_table': 'staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaperPatternQuestion',
            fields=[
                ('paper_pattern_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('paper_pattern_question_text_id', models.IntegerField()),
                ('paper_pattern_question_text', models.TextField()),
                ('rau_type', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('chapter_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.ChapterTopic')),
                ('paper_pattern_entry_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.PaperPatternEntry')),
            ],
            options={
                'db_table': 'paper_pattern_question',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='paperpatternentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Tblsubject'),
        ),
        migrations.CreateModel(
            name='MapTeacherSubject',
            fields=[
                ('map_teacher_subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Tblsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Teacher')),
            ],
            options={
                'db_table': 'map_teacher_subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MapStudentPaperPatternQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark_obtained', models.IntegerField()),
                ('paper_pattern_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.PaperPatternQuestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Student')),
            ],
            options={
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('feedback_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('feedback_question_credit', models.IntegerField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.FeedbackQuestionGroup')),
            ],
            options={
                'db_table': 'feedback_question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_rating', models.IntegerField()),
                ('feedback_comments', models.TextField()),
                ('feedback_date', models.DateTimeField()),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.FeedbackQuestion')),
                ('map_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.MapTeacherSubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.Student')),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chaptertopic',
            name='subject_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.SubjectChapter'),
        ),
    ]
