# Generated by Django 3.0.8 on 2020-10-02 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MySchoolUser',
            fields=[
                ('myschool_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('class_field', models.ForeignKey(db_column='class', on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.TblClass')),
            ],
            options={
                'db_table': 'myschool_user',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='staff',
            name='person',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='student',
            name='person',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='person',
        ),
        migrations.RemoveField(
            model_name='tblrole',
            name='role_type',
        ),
        migrations.AddField(
            model_name='tblrole',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='mapstudentpaperpatternquestion',
            table='map_myschool_user_paper_pattern_question',
        ),
        migrations.AlterModelTable(
            name='mapteachersubject',
            table='map_myschool_user_subject',
        ),
        migrations.AlterModelTable(
            name='tblrole',
            table='tbl_role',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='myschooluser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.TblRole'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.MySchoolUser'),
        ),
        migrations.AlterField(
            model_name='mapstudentpaperpatternquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.MySchoolUser'),
        ),
        migrations.AlterField(
            model_name='mapteachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.MySchoolUser'),
        ),
        migrations.AlterField(
            model_name='studentefficacy',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.MySchoolUser'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
