# Generated by Django 3.1.3 on 2021-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertype',
            name='assessment_type',
            field=models.BooleanField(default=True, help_text='True if is Formative else False'),
        ),
    ]
