# Generated by Django 3.1.3 on 2020-12-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperquestion',
            name='rau_type',
            field=models.CharField(choices=[('R', 'Remembrance'), ('A', 'Application'), ('U', 'Understanding')], max_length=1),
        ),
    ]
