# Generated by Django 3.1.3 on 2020-11-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmyschooluserstandardsection',
            old_name='class_field',
            new_name='standard_section',
        ),
    ]
