# Generated by Django 3.0.8 on 2020-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterTopic',
            fields=[
                ('chapter_topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_id', models.IntegerField()),
                ('topic_name', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'chapter_topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapTeacherSubject',
            fields=[
                ('map_teacher_subject_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'map_teacher_subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarksObtained',
            fields=[
                ('marks_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_gained', models.IntegerField()),
            ],
            options={
                'db_table': 'marks_obtained',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarksType',
            fields=[
                ('marks_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks_type', models.CharField(max_length=15)),
                ('out_of', models.IntegerField()),
            ],
            options={
                'db_table': 'marks_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=25)),
                ('password', models.TextField()),
                ('salt', models.TextField()),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectChapter',
            fields=[
                ('subject_chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=15)),
                ('remembarence_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('chapter_credit', models.IntegerField()),
            ],
            options={
                'db_table': 'subject_chapter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblClass',
            fields=[
                ('class_field', models.CharField(db_column='class', max_length=3, primary_key=True, serialize=False)),
                ('describe', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblrole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tblrole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblsubject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=20)),
                ('remembarence_credit', models.IntegerField()),
                ('applied_knowledge_credit', models.IntegerField()),
                ('understanding_credit', models.IntegerField()),
                ('subject_credit', models.IntegerField()),
            ],
            options={
                'db_table': 'tblsubject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AssessmentCreditObtained',
        ),
        migrations.DeleteModel(
            name='AssessmentType',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='MapSubjectStudent',
        ),
        migrations.DeleteModel(
            name='MapSubjectTeacher',
        ),
        migrations.DeleteModel(
            name='MstRole',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Syllabus',
        ),
        migrations.DeleteModel(
            name='SyllabusTopic',
        ),
    ]
