# Generated by Django 3.1.3 on 2020-12-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0002_auto_20201210_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperentry',
            name='subject',
        ),
        migrations.CreateModel(
            name='MapPaperEntrySubjectChapter',
            fields=[
                ('map_paper_entry_subject_chapter', models.AutoField(primary_key=True, serialize=False)),
                ('paper_entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.paperentry')),
                ('subject_chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.subjectchapter')),
            ],
            options={
                'db_table': 'map_paper_entry_subject_chapter',
            },
        ),
    ]
