# Generated by Django 3.1.3 on 2020-12-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0003_auto_20201210_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperentry',
            old_name='paper_name',
            new_name='paper_entry_name',
        ),
        migrations.RemoveField(
            model_name='paperentry',
            name='paper_status',
        ),
        migrations.AddField(
            model_name='paperentry',
            name='paper_entry_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paperentry',
            name='paper_entry_date',
            field=models.DateField(),
        ),
    ]
