# Generated by Django 3.1.3 on 2020-12-15 06:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0004_auto_20201211_1337'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subjectchapter',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
