# Generated by Django 3.1.3 on 2020-12-15 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0005_auto_20201215_1210'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subjectchapter',
            managers=[
            ],
        ),
    ]
