# Generated by Django 3.1.3 on 2020-12-12 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0005_paperentry_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapstudentpaperpatternentry',
            name='standard_section',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.standardsection'),
            preserve_default=False,
        ),
    ]
