# Generated by Django 3.1.3 on 2020-12-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0006_mapstudentpaperpatternentry_standard_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapmyschooluserstandardsection',
            old_name='map_my_school_user_standard_section',
            new_name='map_my_school_user_standard_section_id',
        ),
    ]
