# Generated by Django 3.1.3 on 2020-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformance', '0007_auto_20201217_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapmyschooluserstandardsection',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
