from aagam_packages.django.model_extensions.utils import register_app_db_models_to_django_admin_site

# Register your models here.
register_app_db_models_to_django_admin_site('StudentPerformancePrediction')