# Generated by Django 3.1.3 on 2020-11-13 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySchoolHome', '0001_initial'),
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestionGroup',
            fields=[
                ('feedback_question_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_group', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'feedback_question_group',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('feedback_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('feedback_question_credit', models.IntegerField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentFeedback.feedbackquestiongroup')),
            ],
            options={
                'db_table': 'feedback_question',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_rating', models.IntegerField()),
                ('feedback_comments', models.TextField()),
                ('feedback_date', models.DateTimeField()),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentFeedback.feedbackquestion')),
                ('map_teacher_subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.mapteachersubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'feedback',
                'managed': True,
            },
        ),
    ]
