# Generated by Django 3.1.3 on 2020-12-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySchoolHome', '0001_initial'),
        ('StudentPerformance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('feedback_form_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_form_date', models.DateField()),
                ('feedback_form_status', models.BooleanField()),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentPerformance.mapmyschoolusersubject')),
            ],
            options={
                'db_table': 'feedback_form',
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionGroup',
            fields=[
                ('feedback_question_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_group', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'feedback_question_group',
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('feedback_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('feedback_question_credit', models.IntegerField()),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentFeedback.feedbackquestiongroup')),
            ],
            options={
                'db_table': 'feedback_question',
            },
        ),
        migrations.CreateModel(
            name='FeedbackFormQuestion',
            fields=[
                ('feedback_form_question_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentFeedback.feedbackform')),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentFeedback.feedbackquestion')),
            ],
            options={
                'db_table': 'feedback_form_question',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_rating', models.IntegerField()),
                ('feedback_comments', models.TextField()),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('feedback_form_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='StudentFeedback.feedbackformquestion')),
                ('myschool_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
