# Generated by Django 3.1.3 on 2020-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='student',
            new_name='myschool_user',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='form_status',
            new_name='feedback_form_status',
        ),
        migrations.RenameField(
            model_name='feedbackformquestion',
            old_name='feedback_form_question',
            new_name='feedback_form_question_id',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='date_created',
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='feedback_form_date',
            field=models.DateField(default="2020-10-10"),
            preserve_default=False,
        ),
    ]
