# Generated by Django 3.1.3 on 2020-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='feedback_form_date',
            field=models.DateField(default="2020-10-10"),
            preserve_default=False,
        ),
    ]
