# Generated by Django 3.1.3 on 2020-12-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentFeedback', '0002_auto_20201211_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='student',
            new_name='myschool_user',
        ),
        migrations.RenameField(
            model_name='feedbackform',
            old_name='form_status',
            new_name='feedback_form_status',
        ),
        migrations.RenameField(
            model_name='feedbackformquestion',
            old_name='feedback_form_question',
            new_name='feedback_form_question_id',
        ),
        migrations.RemoveField(
            model_name='feedbackform',
            name='date_created',
        ),
    ]
