# Generated by Django 3.1.3 on 2021-03-08 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySchoolHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('student_efficacy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('past_marks', models.IntegerField()),
                ('past_marks1', models.IntegerField()),
                ('student_group', models.CharField(max_length=20)),
                ('predictions', models.IntegerField()),
            ],
            options={
                'db_table': 'prediction_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentEfficacy',
            fields=[
                ('student_efficacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_education', models.IntegerField()),
                ('internet_facility', models.IntegerField()),
                ('study_time', models.IntegerField()),
                ('paid_tuition', models.IntegerField()),
                ('past_failures', models.IntegerField()),
                ('free_time', models.IntegerField()),
                ('extra_curricular_activities', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('class_engagement', models.IntegerField()),
                ('health', models.IntegerField()),
                ('past_marks', models.IntegerField(default=20)),
                ('past_marks1', models.IntegerField(default=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'student_efficacy',
                'managed': True,
            },
        ),
    ]
