# Generated by Django 3.1.3 on 2020-12-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MySchoolHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEfficacy',
            fields=[
                ('student_efficacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('father_education', models.IntegerField()),
                ('internet_facility', models.IntegerField()),
                ('study_time', models.IntegerField()),
                ('paid_tuition', models.IntegerField()),
                ('past_failures', models.IntegerField()),
                ('free_time', models.IntegerField()),
                ('extra_curricular_activities', models.IntegerField()),
                ('absences', models.IntegerField()),
                ('class_engagement', models.IntegerField()),
                ('health', models.IntegerField()),
                ('predictions', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='MySchoolHome.myschooluser')),
            ],
            options={
                'db_table': 'student_efficacy',
                'managed': True,
            },
        ),
    ]
