# Generated by Django 3.1.3 on 2020-12-24 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformancePrediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentefficacy',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studentefficacy',
            name='predictions',
        ),
    ]
