# Generated by Django 3.1.3 on 2021-02-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformancePrediction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentefficacy',
            name='group',
        ),
        migrations.AlterField(
            model_name='studentefficacy',
            name='absences',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentefficacy',
            name='class_engagement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentefficacy',
            name='past_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentefficacy',
            name='past_marks1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentefficacy',
            name='predictions',
            field=models.IntegerField(null=True),
        ),
    ]
