# Generated by Django 3.1.3 on 2020-12-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPerformancePrediction', '0002_auto_20201224_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentefficacy',
            name='predictons',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
